name: main

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze .
      - run: dart test
